### ISSUE TITLE
[Feat-FE] 거울모드 페이지 개발

### ISSUE THREAD

**Issue by aa001R** [SIXBACK-SmartMirror/smartmirror#1]
In GitLab by @heymin2 on Sep 9, 2024, 15:06

Feat : 거울모드 페이지 개발

## 📔 Description
- 빈 페이지 & 화면 페이지 반복해서 나오도록 개발
- input 페이지도 같이 나오도록 개발

## 🐈 Todo

- [x] 빈 페이지 & 화면 페이지 개발
- [x] 페이지 일정시간 반복
- [x] output & input 페이지 연결

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 9, 2024, 15:30

mentioned in commit e0591e5826171a20a95de842e42f8aa6c4a0f09a

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 10, 2024, 15:07

mentioned in commit 15f52cf950feb4e58597b974e4f6851038a91704

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 10, 2024, 17:17

marked the checklist item **빈 페이지 & 화면 페이지 개발** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 10, 2024, 17:17

marked the checklist item **페이지 일정시간 반복** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 10, 2024, 17:17

marked the checklist item **output & input 페이지 연결** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 11, 2024, 14:32

mentioned in commit 36c64ec1fb131348ec9562c62edeb449c6e3a760

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 11, 2024, 16:36

mentioned in commit 824928113297a421887b13fa1f960cf0930f0f82

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 13, 2024, 15:38

mentioned in commit 807adde4815e5dcb50537f55a58a2f54518d3eb4
