### ISSUE TITLE
[Feat-FE] input 모니터 연결

### ISSUE THREAD

**Issue by aa001R** [SIXBACK-SmartMirror/smartmirror#13]
In GitLab by @heymin2 on Sep 19, 2024, 13:29

## 📔 Description
- input 모니터 연결
- 연결 후 화면 설정

## 🐈 Todo
- [x] input 모니터 연결
- [x] 연결 후 화면 설정
- [x] 화면 사이즈 변경

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 13:55

mentioned in commit b291b67e2d22d534ab3c638cae11eca3f94a7b8a

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 13:57

created branch [`Feature/Front/15-monitor-shm`](/s11-ai-image-sub1/S11P21D204/-/compare/master...Feature%2FFront%2F15-monitor-shm) to address this issue

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 13:58

created branch [`feature/front/15-monitor-shm`](/s11-ai-image-sub1/S11P21D204/-/compare/master...feature%2Ffront%2F15-monitor-shm) to address this issue

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 14:32

mentioned in commit 18d7929a66dbafcabaa2c36f1b38d5bee1236839

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 14:33

marked the checklist item **input 모니터 연결** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 14:33

marked the checklist item **연결 후 화면 설정** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 16:07

mentioned in commit c2eb34e38656058c3e6042875ce20242064610d8

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 16:40

mentioned in commit d54aabb1e358350c1b0755314bda5dd6693ccfac

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 16:44

marked the checklist item **화면 사이즈 변경** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 17:06

mentioned in commit 06b5e8bd14bb794d87f35f18fe818cf8409c9315

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 20, 2024, 09:36

mentioned in commit 0d3673958022cf555d4065ecb48e41aadb0ee112
