### ISSUE TITLE
[Feat-AI] 커스텀 색깔 합성 AI 모델 구현

### ISSUE THREAD

**Issue by aa001R** [SIXBACK-SmartMirror/smartmirror#18]
In GitLab by @sook000 on Sep 23, 2024, 17:49

## 📔 Description
- 입술 색깔 합성 AI 모델 스크립트 작성
- 입술 색깔 합성 AI 모델 테스트

## 🐈 Todo

- [x] 커스텀 색깔 합성 AI 모델 스크립트 작성
- [x] 커스텀 색깔 합성 AI 모델 테스트
- [x] 커스텀 색깔 합성 API 만들기
- [x] 커스텀 색깔 합성 응답 형식 만들기
- [x] 커스텀 색깔 합성 오류 응답 만들기
- [x] 가상환경 파일 생성

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 23, 2024, 17:51

created branch [`feature/ai/21-lipAiModel-acs`](/s11-ai-image-sub1/S11P21D204/-/compare/master...feature%2Fai%2F21-lipAiModel-acs) to address this issue

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 23, 2024, 17:59

mentioned in commit 287bdbc87a3e1a0b5b29675f699e32a4bfbfb552

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 04:30

mentioned in commit bd47c2001c56c2577eecb2aa80da5fe82cdd3272

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 04:30

mentioned in commit 2f002fd5dc35146403221f7c0f3698aead10121f

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 04:30

mentioned in commit 2d75e271a21909a16f22cbcc04ae4d0a331161a8

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 04:30

mentioned in commit 274fe69ab45209e29f37bb5b10769b27be9d3f5b

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 14:47

mentioned in commit 7c9d993f6f821531634b786d515ba4f1b76ded26

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 14:47

mentioned in commit d8984aa5173c5aee9d14ab9a23c4e03aa30982c2

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 14:47

mentioned in commit 99d8686081e83b2b3d5717e172c0d71aefa4fae8

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 14:47

mentioned in commit d279d0feb2c0ea98a58cb610c629cc186d20e7c8

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 14:47

mentioned in commit 11ff76b2024718c6d9b05b7fee2b91e37864d8e0

**Comment by aa001R** [comment]
In GitLab by @sook000 on Sep 30, 2024, 14:47

mentioned in commit 328a4dfd1dc93c12f06d52f92a5c2574bb7269a2

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 4, 2024, 02:28

mentioned in commit c93f511bfc7b2b78a9af63f17a43218bd6240a4b

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 4, 2024, 02:31

marked the checklist item **커스텀 색깔 합성 AI 모델 스크립트 작성** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 4, 2024, 02:31

marked the checklist item **커스텀 색깔 합성 AI 모델 테스트** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 4, 2024, 02:31

marked the checklist item **커스텀 색깔 합성 API 만들기** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 4, 2024, 02:31

marked the checklist item **커스텀 색깔 합성 응답 형식 만들기** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 4, 2024, 02:31

marked the checklist item **커스텀 색깔 합성 오류 응답 만들기** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 6, 2024, 21:35

mentioned in commit b659b07f1aa7aaa240b1f771e1e520a941cb23b0

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 6, 2024, 21:40

mentioned in commit 348567d5916f3fb1935d8de906759dbe6f1b3864

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 6, 2024, 21:40

mentioned in commit 3e40cd93bddba24113c8e3468946e0d4554f5b66

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 6, 2024, 22:30

marked the checklist item **가상환경 파일 생성** as completed
