### ISSUE TITLE
[Feat-FE] 검색 페이지 개발

### ISSUE THREAD

**Issue by aa001R** [SIXBACK-SmartMirror/smartmirror#2]
In GitLab by @heymin2 on Sep 10, 2024, 17:20

## 📔 Description
- 검색 페이지 디자인
- 검색 조회 디자인
- 음성 인식 후 텍스트로 변경 (stt)
- 키보드로 검색
- 검색 api 연결

## 🐈 Todo

- [x] 검색 페이지 디자인
- [x] 검색 조회 디자인
- [x] 음성 녹음
- [x] 키보드로 검색
- [x] 검색 api 연결

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 10, 2024, 17:22

mentioned in commit 57f40737bcd6de24527b71912e960dc1946d59bc

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 10, 2024, 17:22

mentioned in commit eac753a17760fa4f2dccdbe851f4d2be4fccbd21

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 11, 2024, 15:25

mentioned in commit 8e79a4f9d3353ca352a44c8ad1ad3876d9064c92

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 12, 2024, 10:18

mentioned in commit e54fb0eafa66864b46805b8703f8f498bd6802ee

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 12, 2024, 11:08

mentioned in commit dbd2709ff82b22a4bebe7aaa425866283f479591

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 12, 2024, 12:47

mentioned in commit b9a6c3ef753aa3960baca049a28eb0c2a3697d85

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 12, 2024, 12:47

mentioned in commit 1acf967a7182f6fcbbd627d5da37da1534c7b3c0

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 12, 2024, 14:04

mentioned in commit 93c6117247aef815117565ce407dbfba150bf87f

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 13, 2024, 10:05

marked the checklist item **검색 페이지 디자인** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 13, 2024, 10:05

marked the checklist item **키보드로 검색** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 13, 2024, 11:08

mentioned in commit 0d76ace9b43e5da1186c8e69cf9bc27ef9bb03a1

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 13, 2024, 11:08

mentioned in commit f56ed021de2b20e93389e6253b60eed7402b1f23

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 13, 2024, 15:15

mentioned in commit 268d4fee10cb442655137d74589f2b61249a2b26

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 13, 2024, 15:38

mentioned in commit c2377b0b55f8bf9fda637c8e3ff93a778fa68e2b

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 17:21

created branch [`feature/front/3-search-shm`](/s11-ai-image-sub1/S11P21D204/-/compare/master...feature%2Ffront%2F3-search-shm) to address this issue

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 19, 2024, 17:57

mentioned in commit 50bfcb55d706218499da703ea9c871aa64f1e7b6

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 23, 2024, 09:31

mentioned in commit b7549c6f3585b6647c9f63824f0dce31c991882d

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 23, 2024, 15:28

mentioned in commit 3540c89b4aaa4011d5b4a2640ce05a69bb12c8e1

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 23, 2024, 15:28

mentioned in commit 70adb3bd1ef46c4d05747480717b2d3314ee688b

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 23, 2024, 15:49

mentioned in commit 3bb6b6ae6d76b9958ea92f5eb73b79eedfc1df17

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 23, 2024, 15:57

mentioned in commit 2814ae436fb48a152585dede87699d4bc6e43a85

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 23, 2024, 16:48

mentioned in commit aef2ff68a91ee17ef86818ad193e8f40abb63c91

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 23, 2024, 17:01

marked the checklist item **검색 조회 디자인** as completed

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 23, 2024, 17:03

mentioned in commit 32714c8c624e790363e016be253fde8819ff9bc1

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Sep 24, 2024, 15:04

mentioned in commit 4be7d845c2411f3de7d2e23b72a6117631af76e0

**Comment by aa001R** [comment]
In GitLab by @heymin2 on Oct 2, 2024, 11:41

mentioned in commit 9f60c02de66aa9bb232a34d2cffbe43b2748706b
