### ISSUE TITLE
[Feat-BE] 기록용 mongodb 추가

### ISSUE THREAD

**Issue by aa001R** [SIXBACK-SmartMirror/smartmirror#31]
In GitLab by @sook000 on Oct 6, 2024, 22:38

## 📔 Description
- 입고 기록용 로그
- 판매 기록용 로그
- [선택] qr코드 로그, 스타일 합성 로그, 커스텀 합성 로그
- [선택] qr코드 로그, 스타일 합성 로그, 커스텀 합성 로그 기존 API와 연동
- [선택] 입고 기록용, 판매 기록용 로그 조회 페이지(vue) 

## 🐈 Todo

- [x] 입고 기록용 로그
- [x] 판매 기록용 로그
- [x] [선택] qr코드 로그, 스타일 합성 로그, 커스텀 합성 로그
- [x] [선택] qr코드 로그, 스타일 합성 로그, 커스텀 합성 로그 기존 API와 연결
- [ ] [선택] 입고 기록용, 판매 기록용 로그 조회 페이지(vue)

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 6, 2024, 22:40

created branch [`feature/back/36-mongodb-acs`](/s11-ai-image-sub1/S11P21D204/-/compare/master...feature%2Fback%2F36-mongodb-acs) to address this issue

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 04:25

mentioned in commit 26b961aeea49cb0e4356af995a40bfb54e3f6c6b

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 04:25

mentioned in commit b8056e012c0108218c4ac3fa57108e0f9ffe632d

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 04:25

mentioned in commit 6a2d15616a862afd3a12bde394bf618eac38da1f

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 04:25

mentioned in commit 43cf698e098c278c4eb27ac9a358f79e77f60590

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 04:25

mentioned in commit 1772edc372811cd4129197683c4bbc8027de321c

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 04:25

mentioned in commit a2f5f3b73540e7db526ee5edf2143e7bb5faba22

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 03:09

mentioned in commit fb0872e83eb33ab0051589d853efe02b1b66fc42

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 11:00

mentioned in commit cec57a3b3cef231adee8c5c232c73cb590be61fb

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 11:07

marked the checklist item **입고 기록용 로그** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 11:07

marked the checklist item **판매 기록용 로그** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 11:07

marked the checklist item **[선택] qr코드 로그, 스타일 합성 로그, 커스텀 합성 로그** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 11:07

marked the checklist item **[선택] 입고 기록용, 판매 기록용 로그 조회 페이지(vue)** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 11:07

marked the checklist item **[선택] 입고 기록용, 판매 기록용 로그 조회 페이지(vue)** as incomplete

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 11:11

mentioned in commit 3cdeb9c9617dea1b80675c7d4f1036b7602ab8ae

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 10, 2024, 18:18

marked the checklist item **[선택] qr코드 로그, 스타일 합성 로그, 커스텀 합성 로그 기존 API와 연결** as completed
