### ISSUE TITLE
[Fix-AI] 커스텀 합성 AI 오류 수정, 캐싱

### ISSUE THREAD

**Issue by aa001R** [SIXBACK-SmartMirror/smartmirror#33]
In GitLab by @sook000 on Oct 7, 2024, 22:06

## 📔 Description
- 여러 얼굴 인식될 때 오류 해결하기
- 얼굴 잘라서 크게 보여주기
- 일부 얼굴 부위 인식되지 않을 때 오류 해결하기
- API 응답속도 개선하기 -> 캐싱

## 🐈 Todo

- [x] 여러 얼굴 중에서 가장 큰 얼굴만 인식하기
- [x] 얼굴 잘라서 크게 보여주기
- [x] 특정 얼굴 부위 인식하는 경우에만 합성하기
- [x] 캐싱 통해 API 응답속도 개선하기

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 22:08

created branch [`feature/ai/38-fixCustomAi-acs`](/s11-ai-image-sub1/S11P21D204/-/compare/master...feature%2Fai%2F38-fixCustomAi-acs) to address this issue

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 22:58

marked the checklist item **여러 얼굴 중에서 가장 큰 얼굴만 인식하기** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 7, 2024, 22:58

marked the checklist item **얼굴 잘라서 크게 보여주기** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 01:58

marked the checklist item **특정 얼굴 부위 인식하는 경우에만 합성하기** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 02:17

marked the checklist item **캐싱 통해 API 응답속도 개선하기** as completed

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 02:18

mentioned in commit b32dea57234c29a9269fbed7144b3c8c78932c6a

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 02:18

mentioned in commit 524c3e1214b5847564f69e80fcb5f13b26c8ac97

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 02:18

mentioned in commit 27fd370fb50491e543b0414ead15b287add33b43

**Comment by aa001R** [comment]
In GitLab by @sook000 on Oct 8, 2024, 02:18

mentioned in commit 4f63e344f15d55225e5ca5e8c98f40aa783dd9d4
